// PURPOSE: Docker Host — runs colonies as local Docker containers via the Docker CLI.
// PURPOSE: Each colony gets its own container; environments are volume-mounted or network-accessible.

import { randomUUID } from 'node:crypto';
import { execFile } from 'node:child_process';
import { mkdtemp, writeFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve, relative, isAbsolute } from 'node:path';
import type {
  Host,
  HostMetadata,
  DashboardOptions,
  ColonyDefinition,
  Environment,
  HostResources,
} from '../core/types.js';
import { isSerializableEnvironment } from '../core/environment-registry.js';
import type { ColonyModuleRef } from '../cloud/types.js';

// ── Public interfaces ────────────────────────────────────────

export interface DockerHostConfig {
  /** Docker image (default: 'mandible-colony:latest') */
  image?: string;
  /** Human-readable name (default: 'docker') */
  name?: string;
  /** Project root to volume-mount (default: process.cwd()) */
  projectRoot?: string;
  /** Docker network name */
  network?: string;
  /** Resource limits per container */
  resources?: HostResources;
  /** Timeout waiting for containers (ms, default: 30_000) */
  readyTimeout?: number;
}

export interface DockerHostMetadata extends HostMetadata {
  containers: Record<string, {
    containerId: string;
    state: string;
    image: string;
  }>;
}

// ── Colony entry type (from MandibleBuilder) ─────────────────

interface ColonyEntry {
  name: string;
  configurator?: (builder: any) => any;
  moduleRef?: ColonyModuleRef;
}

// ── Docker CLI helper ────────────────────────────────────────

/** @internal Exported for testing */
export async function dockerExec(args: string[]): Promise<string> {
  return new Promise((resolve, reject) => {
    execFile('docker', args, { maxBuffer: 1024 * 1024 }, (err, stdout, stderr) => {
      if (err) reject(new Error(`docker ${args[0]} failed: ${stderr || err.message}`));
      else resolve(stdout.trim());
    });
  });
}

// ── Runner script generation ─────────────────────────────────

const SAFE_IDENTIFIER = /^[a-zA-Z0-9_\-/.]+$/;

/** @internal Exported for testing */
export function generateRunnerScript(opts: {
  colonyName: string;
  modulePath: string;
  exportName: string;
  moduleArgs?: unknown[];
}): string {
  // Validate interpolated values to prevent template injection
  if (!SAFE_IDENTIFIER.test(opts.colonyName)) {
    throw new Error(`Invalid colony name: "${opts.colonyName}" — must match [a-zA-Z0-9_\\-/.]+`);
  }
  if (!SAFE_IDENTIFIER.test(opts.exportName)) {
    throw new Error(`Invalid export name: "${opts.exportName}" — must match [a-zA-Z0-9_\\-/.]+`);
  }
  if (!SAFE_IDENTIFIER.test(opts.modulePath)) {
    throw new Error(`Invalid module path: "${opts.modulePath}" — must match [a-zA-Z0-9_\\-/.]+`);
  }

  const argsJson = JSON.stringify(opts.moduleArgs ?? []);
  return `// Generated by DockerHost — do not edit
import { createRuntime } from '@mandible-ai/mandible';
import { EventBus } from '@mandible-ai/mandible';
import { colony } from '@mandible-ai/mandible';
import { deserializeEnvironment } from '@mandible-ai/mandible';

// Import all environment adapters so they self-register
import '@mandible-ai/mandible/environments/filesystem/index.js';
import '@mandible-ai/mandible/environments/github/index.js';
import '@mandible-ai/mandible/environments/dolt/index.js';

const envConfig = JSON.parse(process.env.MANDIBLE_COLONY_CONFIG);
const env = deserializeEnvironment(envConfig);

const mod = await import('/workspace/${opts.modulePath}');
const factory = mod['${opts.exportName}'];
const configurator = factory(...${argsJson});
const colonyDef = configurator(colony('${opts.colonyName}')).in(env).build();

const runtime = createRuntime(colonyDef, { eventBus: new EventBus() });
await runtime.start();
console.log('[docker-runner] ${opts.colonyName} running');

const shutdown = async () => { await runtime.stop(); process.exit(0); };
process.on('SIGTERM', shutdown);
process.on('SIGINT', shutdown);
`;
}

// ── Docker run args builder ──────────────────────────────────

/** @internal Exported for testing */
export function buildDockerArgs(opts: {
  containerName: string;
  image: string;
  projectRoot: string;
  runnerDir: string;
  runnerFile: string;
  envConfig: string;
  colonyName: string;
  network?: string;
  resources?: HostResources;
  fsEnvRoot?: string;
}): string[] {
  const args: string[] = [
    'run', '-d',
    '--name', opts.containerName,
    '-v', `${opts.projectRoot}:/workspace`,
    '-v', `${opts.runnerDir}:/app/runners`,
    '-e', `MANDIBLE_COLONY_CONFIG=${opts.envConfig}`,
    '-e', `MANDIBLE_COLONY_NAME=${opts.colonyName}`,
  ];

  // Volume-mount filesystem environment root so containers share signals
  if (opts.fsEnvRoot) {
    args.push('-v', `${opts.fsEnvRoot}:${opts.fsEnvRoot}`);
  }

  if (opts.network) {
    args.push('--network', opts.network);
  }

  if (opts.resources?.maxCpus) {
    args.push('--cpus', String(opts.resources.maxCpus));
  }
  if (opts.resources?.maxMemoryMb) {
    args.push('--memory', `${opts.resources.maxMemoryMb}m`);
  }

  args.push(opts.image);
  args.push('npx', 'tsx', `/app/runners/${opts.runnerFile}`);

  return args;
}

// ── DockerHost class ─────────────────────────────────────────

export class DockerHost implements Host<DockerHostMetadata> {
  readonly name: string;
  private config: DockerHostConfig;
  private containerIds: Map<string, string> = new Map();
  private _colonies: Array<{ name: string; state: string }> = [];
  private _environments: Environment[] = [];
  private _colonyDefs: ColonyDefinition[] = [];
  private _colonyEntries: ColonyEntry[] = [];
  private _tempDir?: string;
  private _metadata: DockerHostMetadata = {
    id: '', startedAt: new Date(0), containers: {},
  };

  constructor(config: DockerHostConfig) {
    this.name = config.name ?? 'docker';
    this.config = config;
  }

  get metadata(): DockerHostMetadata { return this._metadata; }
  get colonies(): Array<{ name: string; state: string }> { return this._colonies; }
  get environments(): Environment[] { return this._environments; }

  /** Called by MandibleBuilder before start(). Stores raw colony entries with module refs. */
  setColonyEntries(entries: ReadonlyArray<Readonly<ColonyEntry>>): void {
    this._colonyEntries = [...entries];
  }

  async start(colonies: ColonyDefinition[]): Promise<void> {
    this._colonyDefs = colonies;

    // Validate all entries have moduleRef (closures can't cross process boundaries)
    for (const entry of this._colonyEntries) {
      if (!entry.moduleRef) {
        throw new Error(
          `Colony "${entry.name}" uses a closure configurator, which cannot run in Docker containers. ` +
          `Use a module reference instead: .colony('${entry.name}', { module: './path.ts', export: 'configureName' })`,
        );
      }
    }

    // Serialize environment config
    const env = colonies[0]?.environment;
    if (!env) throw new Error('No colonies to start');

    const envConfig = isSerializableEnvironment(env) ? env.serialize() : { type: 'unknown', name: env.name };
    const envConfigJson = JSON.stringify(envConfig);

    // Detect filesystem environment for volume mounting
    const isFilesystemEnv = envConfig.type === 'filesystem';
    const fsRoot = isFilesystemEnv ? String(envConfig.root) : undefined;

    // Create temp dir for runner scripts
    this._tempDir = await mkdtemp(join(tmpdir(), 'mandible-docker-'));
    const projectRoot = resolve(this.config.projectRoot ?? process.cwd());
    const image = this.config.image ?? 'mandible-colony:latest';

    // Launch a container per colony
    for (const entry of this._colonyEntries) {
      const ref = entry.moduleRef!;
      const shortId = randomUUID().slice(0, 8);
      const containerName = `mandible-${entry.name}-${shortId}`;

      // Resolve the module path relative to projectRoot
      const modulePath = isAbsolute(ref.module)
        ? relative(projectRoot, ref.module)
        : ref.module;

      // Generate runner script
      const runnerFile = `runner-${entry.name}.ts`;
      const script = generateRunnerScript({
        colonyName: entry.name,
        modulePath,
        exportName: ref.export,
        moduleArgs: ref.args,
      });
      await writeFile(join(this._tempDir, runnerFile), script, 'utf-8');

      // Build docker run args
      const resources = colonies.find(c => c.name === entry.name)?.resources ?? this.config.resources;
      const args = buildDockerArgs({
        containerName,
        image,
        projectRoot,
        runnerDir: this._tempDir,
        runnerFile,
        envConfig: envConfigJson,
        colonyName: entry.name,
        network: this.config.network,
        resources,
        fsEnvRoot: fsRoot,
      });

      // Execute docker run
      const containerId = await dockerExec(args);
      this.containerIds.set(entry.name, containerId);
    }

    // Wait for containers to reach running state
    const timeout = this.config.readyTimeout ?? 30_000;
    const startTime = Date.now();
    while (Date.now() - startTime < timeout) {
      let allRunning = true;
      for (const [name, id] of this.containerIds) {
        const state = await this.getContainerState(id);
        if (state !== 'running') {
          allRunning = false;
          break;
        }
      }
      if (allRunning) break;
      await new Promise(r => setTimeout(r, 500));
    }

    // Collect unique environments
    const envMap = new Map<string, Environment>();
    for (const def of colonies) {
      envMap.set(def.environment.name, def.environment);
    }
    this._environments = Array.from(envMap.values());

    // Build colony state and metadata
    const containers: Record<string, { containerId: string; state: string; image: string }> = {};
    for (const [name, id] of this.containerIds) {
      const state = await this.getContainerState(id);
      this._colonies.push({ name, state });
      containers[name] = { containerId: id, state, image };
    }

    this._metadata = {
      id: randomUUID(),
      startedAt: new Date(),
      containers,
    };
  }

  async stop(): Promise<void> {
    // Stop and remove all containers
    for (const [name, id] of this.containerIds) {
      try {
        await dockerExec(['stop', id]);
      } catch { /* container may already be stopped */ }
      try {
        await dockerExec(['rm', '-f', id]);
      } catch { /* container may already be removed */ }
    }
    this.containerIds.clear();
    this._colonies = [];

    // Clean up temp dir
    if (this._tempDir) {
      try {
        await rm(this._tempDir, { recursive: true, force: true });
      } catch { /* best effort */ }
      this._tempDir = undefined;
    }
  }

  async dashboard(options?: DashboardOptions): Promise<void> {
    const port = options?.port ?? 4040;
    const open = options?.open ?? true;
    const { startDashboard, LocalDashboardSource } = await import('../cli/server.js');
    const { EventBus } = await import('../core/events.js');
    if (this._environments.length === 0) throw new Error('No environments to observe');

    const eventBus = new EventBus();
    // Wire environment onEvent to the bus (if supported)
    for (const env of this._environments) {
      if ('onEvent' in env && typeof (env as any).onEvent === 'function') {
        (env as any).onEvent((event: any) => eventBus.emit(event));
      }
    }

    const emptyStats = {
      signalsSensed: 0, signalsClaimed: 0, signalsProcessed: 0,
      signalsDeposited: 0, claimConflicts: 0, errors: 0, avgProcessingMs: 0,
    };

    const source = new LocalDashboardSource(
      eventBus,
      this._environments,
      () => this._colonies.map(c => ({
        name: c.name,
        state: c.state,
        activeCount: 0,
        concurrency: (() => {
          const cc = this._colonyDefs.find(d => d.name === c.name)?.concurrency ?? 1;
          return typeof cc === 'number' ? cc : (cc.target ?? cc.min);
        })(),
        stats: emptyStats,
      })),
    );
    await startDashboard(source, { port, open });
  }

  private async getContainerState(containerId: string): Promise<string> {
    try {
      const result = await dockerExec(['inspect', '--format', '{{.State.Status}}', containerId]);
      return result;
    } catch {
      return 'unknown';
    }
  }
}

/**
 * Create a Docker host that runs colonies as local Docker containers.
 *
 * @example
 * await mandible('my-swarm')
 *   .environment(env)
 *   .host(docker({ image: 'mandible-colony:latest' }))
 *   .colony('worker', { module: './worker.ts', export: 'configureWorker' })
 *   .start();
 */
export function docker(config?: DockerHostConfig): DockerHost {
  return new DockerHost(config ?? {});
}
